
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGNMENT LBRACE RBRACE VARobject_statement : VAR LBRACE statements RBRACE statementsstatements : variable_expression statements\n                  | object_statement\n                  | emptyvariable_expression : VAR ASSIGNMENTempty :'
    
_lr_action_items = {'VAR':([0,3,6,9,10,],[2,4,4,-5,4,]),'$end':([1,6,7,8,9,10,11,12,],[0,-6,-3,-4,-5,-6,-2,-1,]),'LBRACE':([2,4,],[3,3,]),'RBRACE':([3,5,6,7,8,9,10,11,12,],[-6,10,-6,-3,-4,-5,-6,-2,-1,]),'ASSIGNMENT':([4,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object_statement':([0,3,6,10,],[1,7,7,7,]),'statements':([3,6,10,],[5,11,12,]),'variable_expression':([3,6,10,],[6,6,6,]),'empty':([3,6,10,],[8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> object_statement","S'",1,None,None,None),
  ('object_statement -> VAR LBRACE statements RBRACE statements','object_statement',5,'p_expression_object','parser.py',13),
  ('statements -> variable_expression statements','statements',2,'p_expression_statement_list','parser.py',30),
  ('statements -> object_statement','statements',1,'p_expression_statement_list','parser.py',31),
  ('statements -> empty','statements',1,'p_expression_statement_list','parser.py',32),
  ('variable_expression -> VAR ASSIGNMENT','variable_expression',2,'p_expression_assignment','parser.py',47),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',52),
]
