
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUAL LBRACE RBRACE VARexpression : VAR LBRACE expression RBRACEexpression : VAR EQUAL VARexpression : expression expression'
    
_lr_action_items = {'VAR':([0,1,3,4,5,6,7,8,],[2,2,2,2,7,2,-2,-1,]),'$end':([1,3,7,8,],[0,-3,-2,-1,]),'LBRACE':([2,],[4,]),'EQUAL':([2,],[5,]),'RBRACE':([3,6,7,8,],[-3,8,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,3,4,6,],[1,3,3,6,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VAR LBRACE expression RBRACE','expression',4,'p_expression_expr','parser.py',13),
  ('expression -> VAR EQUAL VAR','expression',3,'p_expression_equal','parser.py',18),
  ('expression -> expression expression','expression',2,'p_expression_expansion','parser.py',23),
]
